name: Docker Image CI

on: workflow_dispatch
permissions:
      id-token: write
      contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag harwincu/harfullstack:v2
    - name: docker login
      run: docker login -u ${{ secrets.USER }} -p ${{ secrets.PASSW }}
    - name: docker push 
      run: docker image push --tag harwincu/harfullstack:v2

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure WebApp
        uses: Azure/webapps-deploy@v3.0.1
        with:
          # Name of the Azure Web App
          app-name: 'harfullstack'
          images: 'harwincu/harfullstack:v2'
          resource-group-name: 'Lab_fullstack'

                
